#!/bin/bash
# SPDX-License-Identifier: AGPL-3.0-or-later
# SPDX-FileCopyrightText: 2021 grommunio GmbH

setup_repo() {

  echo
  echo -e " \x1b[36m▼\x1b[0m grommunio-setup is updating the system"
  echo
  kr=/usr/share/keyrings/download.grommunio.com.gpg
  if [ ! -f $kr ]; then
  wget -qO - https://download.grommunio.com/RPM-GPG-KEY-grommunio | \
    gpg --dearmor --output $kr
  fi
cat << SOURCES > /etc/apt/sources.list.d/grommunio-community.sources
Types: deb
URIs: https://download.grommunio.com/community/Debian_11
Suites: Debian_11
Components: main
Signed-By: $kr
SOURCES

  apt-get update >> "${LOGFILE}" 2>&1
  apt-get install -y "${PACKAGES[@]}" >> "${LOGFILE}" 2>&1
  dpkg -i "${DATADIR}/temp_packages/grommunio-antispam_amd64.deb"
  echo
  echo -e " \x1b[36m▼\x1b[0m operation completed"
  echo
  # keep visual output on the screen for a glimpse so admin can decide
  # if the logfile needs to be inspected.
  sleep 1
}
